# Generated by Django 5.2.7 on 2025-11-04 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="logos/"),
        ),
        migrations.AlterField(
            model_name="store",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
