# Generated by Django 5.2.7 on 2025-10-27 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="rating",
        ),
        migrations.AlterField(
            model_name="review",
            name="is_verified_purchase",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="review",
            name="title",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
